HOST_MODBUS_TCP = "localhost"
PORT_MODBUS_TCP = 502
TYPE_MODBUS = "tcp"

LOWER_CONVEYOR = 1
UPPER_CONVEYOR = 2
INFORMATION_UPPER = 3
INFORMATION_LOWER = 4

MACHINE_TYPE = "unloader"
POSITION_CHECK = "lower"
LOCATION = "LM01"
DESTINATION = "LM02"
LINE_ACTION = "flip"

DESTINATION_HOST = "0.0.0.0"
DESTINATION_PORT = 5000

PI_DESTINATION_HOST = "0.0.0.0"
PI_DESTINATION_PORT = 5000